"""floor signals

Revision ID: 2ede1b3cfa07
Revises: e6e70cbf8160
Create Date: 2026-07-16 17:42:23.481710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ede1b3cfa07'
down_revision: Union[str, None] = 'e6e70cbf8160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_signals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_floor_market_observed', 'floor_signals', ['market_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_floor_market_observed', table_name='floor_signals')
    op.drop_table('floor_signals')
