"""initial schema

Revision ID: 46942500d2d0
Revises: 
Create Date: 2026-07-16 03:31:46.690347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46942500d2d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('coverage_level', sa.Enum('MONITORING', 'RECOMMENDATIONS', name='coveragelevel', native_enum=False, length=20), nullable=False),
    sa.Column('center_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('center_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('radius_km', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('active_sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('competitor_listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_listing_id', sa.String(length=200), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_listing_id')
    )
    op.create_index(op.f('ix_competitor_listings_market_id'), 'competitor_listings', ['market_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('impact_strength', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('curation_status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', name='curationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_market_id'), 'events', ['market_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.Enum('APARTMENT', 'GUESTHOUSE', 'ROOM', name='propertytype', native_enum=False, length=20), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ical_url', sa.String(length=1000), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_account_id'), 'properties', ['account_id'], unique=False)
    op.create_index(op.f('ix_properties_market_id'), 'properties', ['market_id'], unique=False)
    op.create_table('reports_sent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('WEEKLY', 'ALERT', name='reportkind', native_enum=False, length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_sent_account_id'), 'reports_sent', ['account_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', name='subscriptionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('price_per_property', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_account_id'), 'subscriptions', ['account_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_table('price_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('stay_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['competitor_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_obs_listing_stay', 'price_observations', ['listing_id', 'stay_date', 'observed_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('stay_date', sa.Date(), nullable=False),
    sa.Column('recommended_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('previous_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('explanation_template_key', sa.String(length=100), nullable=False),
    sa.Column('explanation_params', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='recommendationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_sold', sa.Boolean(), nullable=True),
    sa.Column('revenue_delta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_account_id'), 'recommendations', ['account_id'], unique=False)
    op.create_index(op.f('ix_recommendations_property_id'), 'recommendations', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_property_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_account_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_price_obs_listing_stay', table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_account_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_reports_sent_account_id'), table_name='reports_sent')
    op.drop_table('reports_sent')
    op.drop_index(op.f('ix_properties_market_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_account_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_events_market_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_competitor_listings_market_id'), table_name='competitor_listings')
    op.drop_table('competitor_listings')
    op.drop_table('markets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
