"""calendar days and listing distance

Revision ID: e9c194e896d9
Revises: 46942500d2d0
Create Date: 2026-07-16 04:19:51.426271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9c194e896d9'
down_revision: Union[str, None] = '46942500d2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('stay_date', sa.Date(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'stay_date')
    )
    op.create_index(op.f('ix_calendar_days_account_id'), 'calendar_days', ['account_id'], unique=False)
    op.create_index(op.f('ix_calendar_days_property_id'), 'calendar_days', ['property_id'], unique=False)
    op.add_column('competitor_listings', sa.Column('distance_center_km', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_listings', 'distance_center_km')
    op.drop_index(op.f('ix_calendar_days_property_id'), table_name='calendar_days')
    op.drop_index(op.f('ix_calendar_days_account_id'), table_name='calendar_days')
    op.drop_table('calendar_days')
    # ### end Alembic commands ###
